# Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: ""
# baseurl: ""
# url: ""
# twitter_username: ""
# github_username:  jekyll

# Build settings
markdown: kramdown

lang:
    de:
        page:
            material    : Material
            dimensions  : Maße (L x B x H mm)
            treatment   : Veredelung
            colours     : Farbe
            designers   : Designers
            price       : Preis