# Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: ""
# baseurl: ""
# url: ""
# twitter_username: ""
# github_username:  jekyll

lang    : de
# Build settings
markdown: kramdown

locale:
    de:
        material    : Material
        size        : Maße (L x B x H mm)
        treatment   : Veredelung
        colours     : Farbe
        designers   : Designers
        advisors    : Vorentwicklung
        price       : Preis
        contact     : Kontakt
        imprint     : Impressum
        moto        : "Schlicht, bedeutet, sich auf das Wesentliche beschränken. Rein. Pur. Ungekünstelt und bescheiden. <br>Möbel, die für sich sprechen, die keiner großen Worte bedürfen: <br>Schlicht."


    en:
        material    : Material
        size        : Size (L x W x H mm)
        treatment   : Treatment
        colours     : Colours
        designers   : Designers
        advisors    : Advisors
        price       : Price
        contact     : Contact
        imprint     : Legal
        moto        : Lorem ipsum dolor sit amet