# Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: ""
# baseurl: ""
# url: ""
# twitter_username: ""
# github_username:  jekyll

# Build settings
markdown: kramdown

lang:
    de:
        page:
            material    : Material
            size        : Maße (L x B x H mm)
            treatment   : Veredelung
            colours     : Farbe
            designers   : Designers
            advisors    : Vorentwicklung
            price       : Preis

    en:
        page:
            material    : Material
            size        : Size (L x W x H mm)
            treatment   : Treatment
            colours     : Colours
            designers   : Designers
            advisors    : Advisors
            price       : Price